# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81f3bd3b8dd2098eb3e96fa975f644a1ceded55af7f639b57e777850bda2fe11bfefba5038be5da8c4b519f4bd3939349bdf2c0854654d87bc043712c1a92b8f

test:
  secret_key_base: 948cd2eeeb38cabefdeb1b4f7abf3db24bf84d57323c05a0ef6bf9171fda13a5114216f2481f5b836e61acd367595941edde160260d77062788bfc6d759e94c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
